name = "sigma637"
compatibility_date = "2024-11-01"

pages_build_output_dir = "public"   # folder with your HTML/CSS/JS

[[d1_databases]]
binding = "DB"
database_name = "accounts"
database_id = "b5b4bde2-ec1f-46d5-8077-7fb6180883dc"
